### Views ###
  Cameras:
      view: yes
      name: Cameras
      entities:
        - group.droidvideo
        - group.cam_control
        - group.cam_sensors
        - weblink.zoneminder
  GardenWatch:
      view: yes
      name: Garden Watch
      entities:
        - group.climate
        - group.catnip1
        - group.catnip2
        - group.toptable
        - group.centertable
        - group.bottomtable
        - group.passion_fruit
        - group.rosemary
        - group.tomato_pot
        - group.tilapia_tank
        - group.koipond
        - camera.tilapia_tank
        - camera.koi_cam
        - camera.garden_cam
  TreeWatch:
      view: yes
      name: Tree Watch
      entities:
        - group.climate
        - group.tree1
        - group.tree2
        - group.tree3
        - group.tree4
        - group.tree5
### Groups ###
  Cam Sensors:
    entities:
    - sensor.koi_cam_video_connections
    - sensor.koi_cam_audio_connections
    - sensor.tilapia_cam_video_connections
    - sensor.tilapia_cam_audio_connections
  DroidVideo:
    name: Video Cams
    entities:
    - camera.tilapia_cam
    - camera.koi_cam
  speed_test:
    name: Speed Test
    entities:
    - sensor.speedtest_download
    - sensor.speedtest_ping
    - sensor.speedtest_upload
  climate:
    name: Climate
    entities:
    - sun.sun
    - sensor.moon
    - sensor.yweather_current
    - sensor.yweather_humidity
    - sensor.yweather_pressure
    - sensor.yweather_temperature
    - sensor.yweather_visibility
    - sensor.yweather_wind_speed
#### MiFlora Groups ####
  catnip1:
    name: CatNip 1
    entities:
    - sensor.catnip_1_battery
    - sensor.catnip_1_conductivity
    - sensor.catnip_1_light_intensity
    - sensor.catnip_1_moisture
    - sensor.catnip_1_temperature
  catnip2:
    name: CatNip 2
    entities:
    - sensor.catnip_2_battery
    - sensor.catnip_2_conductivity
    - sensor.catnip_2_light_intensity
    - sensor.catnip_2_moisture
    - sensor.catnip_2_temperature
  toptable:
    name: Top Table
    entities:
    - sensor.top_table_battery
    - sensor.top_table_conductivity
    - sensor.top_table_light_intensity
    - sensor.top_table_moisture
    - sensor.top_table_temperature
  centertable:
    name: Center Table
    entities:
    - sensor.center_table_battery
    - sensor.center_table_conductivity
    - sensor.center_table_light_intensity
    - sensor.center_table_moisture
    - sensor.center_table_temperature
  bottomtable:
    name: Bottom Table
    entities:
    - sensor.bottom_table_battery
    - sensor.bottom_table_conductivity
    - sensor.bottom_table_light_intensity
    - sensor.bottom_table_moisture
    - sensor.bottom_table_temperature
  tilapia_tank:
    name: Tilapia Tank
    entities:
    - sensor.tilapia_tank_battery
    - sensor.tilapia_tank_conductivity
    - sensor.tilapia_tank_light_intensity
    - sensor.tilapia_tank_moisture
    - sensor.tilapia_tank_temperature
  koipond:
    name: Koi Pond
    entities:
    - sensor.pond_battery
    - sensor.pond_conductivity
    - sensor.pond_light_intensity
    - sensor.pond_moisture
    - sensor.pond_temperature
  rosemary:
    name: Rosemary
    entities:
    - sensor.rosemary_battery
    - sensor.rosemary_conductivity
    - sensor.rosemary_light_intensity
    - sensor.rosemary_moisture
    - sensor.rosemary_temperature
  passion_fruit:
    name: Passion Fruit
    entities:
    - sensor.passion_fruit_battery
    - sensor.passion_fruit_conductivity
    - sensor.passion_fruit_light_intensity
    - sensor.passion_fruit_moisture
    - sensor.passion_fruit_temperature
  tomato_pot:
    name: Tomato Pot
    entities:
    - sensor.tomato_pot_battery
    - sensor.tomato_pot_conductivity
    - sensor.tomato_pot_light_intensity
    - sensor.tomato_pot_moisture
    - sensor.tomato_pot_temperature
  tree1:
    name: Tree 1
    entities:
    - sensor.tree_1_battery
    - sensor.tree_1_conductivity
    - sensor.tree_1_light_intensity
    - sensor.tree_1_moisture
    - sensor.tree_1_temperature
  tree2:
    name: Tree 2
    entities:
    - sensor.tree_2_battery
    - sensor.tree_2_conductivity
    - sensor.tree_2_light_intensity
    - sensor.tree_2_moisture
    - sensor.tree_2_temperature
  tree3:
    name: Tree 3
    entities:
    - sensor.tree_3_battery
    - sensor.tree_3_conductivity
    - sensor.tree_3_light_intensity
    - sensor.tree_3_moisture
    - sensor.tree_3_temperature
  tree4:
    name: Tree 4
    entities:
    - sensor.tree_4_battery
    - sensor.tree_4_conductivity
    - sensor.tree_4_light_intensity
    - sensor.tree_4_moisture
    - sensor.tree_4_temperature
  tree5:
    name: Tree 5
    entities:
    - sensor.tree_5_battery
    - sensor.tree_5_conductivity
    - sensor.tree_5_light_intensity
    - sensor.tree_5_moisture
    - sensor.tree_5_temperature
