#mqtt:
  broker: !secret mqtt_broker
  #port: 16114
  client_id: shed
  #username: core_ha
  #password: !secret mqtt_pass
  birth_message:
    topic: 'shed/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'shed/status'
    payload: 'offline'
    qos: 1
    retain: true
