# Example configuration.yaml entry
#plant:
  TilapiaTank:
    sensors:
      moisture: sensor.tilapia_tank_moisture_2
      battery: sensor.tilapia_tank_battery
      temperature: sensor.tilapia_tank_temperature
      conductivity: sensor.tilapia_tank_conductivity
      brightness: sensor.tilapia_tank_light_intensity
    min_moisture: 0
    max_moisture: 4
    min_battery: 33
    min_conductivity: 0
    min_temperature: 60
  TopTable:
    sensors:
      moisture: sensor.top_table_moisture
      battery: sensor.top_table_battery
      temperature: sensor.top_table_temperature
      conductivity: sensor.top_table_conductivity
      brightness: sensor.top_table_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  CenterTable:
    sensors:
      moisture: sensor.center_table_moisture
      battery: sensor.center_table_battery
      temperature: sensor.center_table_temperature
      conductivity: sensor.center_table_conductivity
      brightness: sensor.center_table_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  BottomTable:
    sensors:
      moisture: sensor.bottom_table_moisture
      battery: sensor.bottom_table_battery
      temperature: sensor.bottom_table_temperature
      conductivity: sensor.bottom_table_conductivity
      brightness: sensor.bottom_table_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  koi_pond:
    sensors:
      moisture: sensor.pond_moisture
      battery: sensor.pond_battery
      temperature: sensor.pond_temperature
      conductivity: sensor.pond_conductivity
      brightness: sensor.pond_light_intensity
    min_moisture: 0
    max_moisture: 10
    min_battery: 33
    min_conductivity: 0
    min_temperature: 60
  TomatoPot:
    sensors:
      moisture: sensor.tomato_pot_moisture
      battery: sensor.tomato_pot_battery
      temperature: sensor.tomato_pot_temperature
      conductivity: sensor.tomato_pot_conductivity
      brightness: sensor.tomato_pot_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  CatNip1:
    sensors:
      moisture: sensor.catnip_1_moisture
      battery: sensor.catnip_1_battery
      temperature: sensor.catnip_1_temperature
      conductivity: sensor.catnip_1_conductivity
      brightness: sensor.catnip_1_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  CatNip2:
    sensors:
      moisture: sensor.catnip_2_moisture
      battery: sensor.catnip_2_battery
      temperature: sensor.catnip_2_temperature
      conductivity: sensor.catnip_2_conductivity
      brightness: sensor.catnip_2_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Rosemary:
    sensors:
      moisture: sensor.rosemary_moisture
      battery: sensor.rosemary_battery
      temperature: sensor.rosemary_temperature
      conductivity: sensor.rosemary_conductivity
      brightness: sensor.rosemary_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  PassionFruit:
    sensors:
      moisture: sensor.passion_fruit_moisture
      battery: sensor.passion_fruit_battery
      temperature: sensor.passion_fruit_temperature
      conductivity: sensor.passion_fruit_conductivity
      brightness: sensor.passion_fruit_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Tree1:
    sensors:
      moisture: sensor.tree_1_moisture
      battery: sensor.tree_1_battery
      temperature: sensor.tree_1_temperature
      conductivity: sensor.tree_1_conductivity
      brightness: sensor.tree_1_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Tree2:
    sensors:
      moisture: sensor.tree_2_moisture
      battery: sensor.tree_2_battery
      temperature: sensor.tree_2_temperature
      conductivity: sensor.tree_2_conductivity
      brightness: sensor.tree_2_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Tree3:
    sensors:
      moisture: sensor.tree_3_moisture
      battery: sensor.tree_3_battery
      temperature: sensor.tree_3_temperature
      conductivity: sensor.tree_3_conductivity
      brightness: sensor.tree_3_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Tree4:
    sensors:
      moisture: sensor.tree_4_moisture
      battery: sensor.tree_4_battery
      temperature: sensor.tree_4_temperature
      conductivity: sensor.tree_4_conductivity
      brightness: sensor.tree_4_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
  Tree5:
    sensors:
      moisture: sensor.tree_5_moisture
      battery: sensor.tree_5_battery
      temperature: sensor.tree_5_temperature
      conductivity: sensor.tree_5_conductivity
      brightness: sensor.tree_5_light_intensity
    min_moisture: 20
    max_moisture: 90
    min_battery: 33
    min_conductivity: 100
    min_temperature: 60
