
- platform: broadlink
  host: emote
  mac: 'B4:43:0D:EF:9E:73'
  timeout: 60
  switches:
    tv:
      friendly_name: "UpStar"
      command_on: 'JgB0AAABLpITExEUExISFBITEhQSExEUEzcTNxM3EzcTNxM3ExMSOBITExMSNhQ4ETkSExMSExMSOBI4EhMSExMTEjgSOBI4EwAFOAABLkoSAAorCwACCgABLkoTAAKVCwAJnAABMUoTAAnvDAACRAABLkoTAA0FAAAAAA==JgB0AAABLpITExEUExISFBITEhQSExEUEzcTNxM3EzcTNxM3ExMSOBITExMSNhQ4ETkSExMSExMSOBI4EhMSExMTEjgSOBI4EwAFOAABLkoSAAorCwACCgABLkoTAAKVCwAJnAABMUoTAAnvDAACRAABLkoTAA0FAAAAAA=='
      command_off: 'JgB0AAABLpITExEUExISFBITEhQSExEUEzcTNxM3EzcTNxM3ExMSOBITExMSNhQ4ETkSExMSExMSOBI4EhMSExMTEjgSOBI4EwAFOAABLkoSAAorCwACCgABLkoTAAKVCwAJnAABMUoTAAnvDAACRAABLkoTAA0FAAAAAA==JgB0AAABLpITExEUExISFBITEhQSExEUEzcTNxM3EzcTNxM3ExMSOBITExMSNhQ4ETkSExMSExMSOBI4EhMSExMTEjgSOBI4EwAFOAABLkoSAAorCwACCgABLkoTAAKVCwAJnAABMUoTAAnvDAACRAABLkoTAA0FAAAAAA=='
    tv_plasma:
      friendly_name: "Plasma"
      command_on:  'JgDgAAwABhIAARWNERIQNRATEDURExA1ERIRNBE1EBMRNBATEDYQExA1EBMQExATETUQNRA1ERISEhATEDUQNRESEhIQExA1EDURNRAAA1MAARWMEhERNRATEjMREhE1EBMQNRA2EBMQNRESEDURExAzExIQExATEDYRNBE0ERIREhIRETUQNRATERIRExE0EDUQNhAAA1IAAReLERIRNRATEDUQExA2ERATNBA1ERIRNRATEDUREhE1EBMQExATEDURNRE0EBMREhESETUQNRATEBMQExE1ETQQNREACc4LAA0FAAAAAAAAAAA='
      command_off: 'JgDgAAwABhIAARWNERIQNRATEDURExA1ERIRNBE1EBMRNBATEDYQExA1EBMQExATETUQNRA1ERISEhATEDUQNRESEhIQExA1EDURNRAAA1MAARWMEhERNRATEjMREhE1EBMQNRA2EBMQNRESEDURExAzExIQExATEDYRNBE0ERIREhIRETUQNRATERIRExE0EDUQNhAAA1IAAReLERIRNRATEDUQExA2ERATNBA1ERIRNRATEDUREhE1EBMQExATEDURNRE0EBMREhESETUQNRATEBMQExE1ETQQNREACc4LAA0FAAAAAAAAAAA='
    tv_emerson:
      friendly_name: "Emerson"
      command_on:  'JgBYAAABIpQSERMTEjcSExISERMRFBE4ERMSExISERQRExE4EjcSNxEUERMSExEUERMROBETERURNxE4ETgSNxI1FBISNxI3EgAFgAABI0sRAAwzAAEiTBIADQU='
      command_off: 'JgBYAAABIpQSERMTEjcSExISERMRFBE4ERMSExISERQRExE4EjcSNxEUERMSExEUERMROBETERURNxE4ETgSNxI1FBISNxI3EgAFgAABI0sRAAwzAAEiTBIADQU='
#    tv_usleep:
#      friendly_name: "USleep"
#      command_on:  'JgBYAAABIpQSERMTEjcSExISERMRFBE4ERMSExISERQRExE4EjcSNxEUERMSExEUERMROBETERURNxE4ETgSNxI1FBISNxI3EgAFgAABI0sRAAwzAAEiTBIADQU='
#      command_off: 'JgBYAAABIpQSERMTEjcSExISERMRFBE4ERMSExISERQRExE4EjcSNxEUERMSExEUERMROBETERURNxE4ETgSNxI1FBISNxI3EgAFgAABI0sRAAwzAAEiTBIADQU='
#    tv_usleep:
#      friendly_name: "USleep"
#      command_on:  '260054000c0006c800012e93121313121313121312131313121313121337133713371337133713371313123812371337133713131337131213121313111412131313123812131238113913371200053700012e4a12000d0500000000'
#      command_off: '260054000c0006c800012e93121313121313121312131313121313121337133713371337133713371313123812371337133713131337131213121313111412131313123812131238113913371200053700012e4a12000d0500000000'
    tv_usleep:
      friendly_name: "Sleep"
      command_on:  'JgBYAAABL5QTExMSExMTEhMTExMSExMTEjgTNxM4EzcTOBI4ExMSOBI4EzgSOBMTEzcTExITExMSExMTEhMTNxMTEzcTOBM3EwAFPwABL0sSAAxQAAEvSxMADQU='
      command_off: 'JgBYAAABL5QTExMSExMTEhMTExMSExMTEjgTNxM4EzcTOBI4ExMSOBI4EzgSOBMTEzcTExITExMSExMTEhMTNxMTEzcTOBM3EwAFPwABL0sSAAxQAAEvSxMADQU='
