alias: Start Media Grab
initial_state: True
trigger:
  platform: state
  entity_id: input_boolean.grab_start
  to: 'on'
  from: 'off'
action:
- service: shell_command.media_grab_start
- service: input_boolean.turn_off
  entity_id: input_boolean.grab_start
