alias: Notify ShortStick
trigger:
  platform: state
  entity_id:
    - sensor.hive_ram_use
    - sensor.shed_ram_use
    - sensor.pepper_ram_use
    - sensor.help_ram_use
    - sensor.ovh_ram_use
    - sensor.prime_ram_use
condition:
  - condition: or
    conditions:
      - condition: numeric_state
        entity_id: sensor.hive_ram_use
        above: 85
      - condition: numeric_state
        entity_id: sensor.shed_ram_use
        above: 85
      - condition: numeric_state
        entity_id: sensor.pepper_ram_use
        above: 85
      - condition: numeric_state
        entity_id: sensor.help_ram_use
        above: 85
      - condition: numeric_state
        entity_id: sensor.ovh_ram_use
        above: 85
      - condition: numeric_state
        entity_id: sensor.prime_ram_use
        above: 85
action:
- service: notify.shortstick
  data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}%"
        title: Check the servers
