alias: Slack the Cat
initial_state: True
trigger:
  platform: state
  entity_id:
    - sensor.cat_cam_motion
    - sensor.cat_cam_battery_level
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.cat_cam_motion
        above: 210
      - condition: numeric_state
        entity_id: sensor.cat_cam_battery_level
        above: 65
action:
- service: notify.hive_cat_slack
  data_template:
    message: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}%"
    title: Chewy
    data:
      file:
        url: http://catcam:8080/shot.jpg
  #    auth: digest
