automation:
  - alias: Stream Casting
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.notify_catcast
          - input_boolean.notify_doorcast
          - input_boolean.notify_gardencast
          - input_boolean.notify_koicast
        to: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.emerson
      - service: shell_command.stream
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.turn_on
        data:
          entity_id: script.off_emerson
