# Weather Prediction
#sensor:
#  platform: yr
#  - platform: yr
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness
#      - lowClouds
#      - mediumClouds
#      - highClouds
#      - dewpointTemperature
  - platform: speedtest
    minute:
      - 0
      - 59
    monitored_conditions:
      - ping
      - download
      - upload
#  - platform: openweathermap
#    api_key: ddd6718fd67a05ee6e1c89994d9e5269
#    monitored_conditions:
#      - weather
  - platform: moon
  - platform: yweather
    monitored_conditions:
#      - weather
      - weather_current
#      - temp_min
#      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature
  - platform: broadlink
    update_interval: 60
    host: emote
    mac: 'B4:43:0D:EF:9E:73'
    monitored_conditions:
      - temperature
  - platform: zoneminder
  - platform: haveibeenpwned
    email:
      !secret email_1
  - platform: haveibeenpwned
    email:
      !secret email_2
  - platform: haveibeenpwned
    email:
      !secret email_3
  - platform: ohmconnect
    id: !secret ohm_id
    binary_sensor:
  #- platform: rest
  #  name: Front Door Motion
  #  sensor_class: motion
  #  resource: http://192.168.0.113:8080/sensors.json?sense=motion_active
  #  value_template: '{{ value_json.motion_active.data[0][1][0] | round(0) }}'
  - platform: glances
    host: shed
    name: shed
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
    #  - 'swap_use'
    #  - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: hive
    name: hive
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
    #  - 'swap_use'
    #  - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: help.davedaley.com
    name: help
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
    #  - 'swap_use'
    #  - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: pepper.davedaley.com
    name: pepper
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
  #    - 'swap_use'
  #    - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: ovh.davedaley.com
    name: ovh
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
    #  - 'swap_use'
    #  - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: glances
    host: prime.optincall.com
    name: prime
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
    #  - 'memory_use'
    #  - 'memory_free'
      - 'swap_use_percent'
    #  - 'swap_use'
    #  - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
  - platform: zabbix
    triggers:
### SSL Cert Check - Owned ###
  - platform: cert_expiry
    host: davedaley.com
    name: davedaley.com
  - platform: cert_expiry
    host: onerealfunnyguy.com
    name: orfg
  - platform: cert_expiry
    host: litterbox.co
    name: litterbox.co
  - platform: cert_expiry
    host: b-e-h.co
    name: b-e-h.co
  - platform: cert_expiry
    host: joeydaley.com
    name: joeydaley.com
  - platform: cert_expiry
    host: flashhunt.com
    name: flashhunt.com
  - platform: cert_expiry
    host: froggyfarms.com
    name: froggyfarms.com
  - platform: cert_expiry
    host: cdrblk.com
    name: cdrblk.com
  - platform: cert_expiry
    host: chronictrackers.com
    name: chronictrackers.com
  - platform: cert_expiry
    host: cart.chronictrackers.com
    name: cart.chronictrackers.com
  - platform: cert_expiry
    host: cannablisscream.com
    name: cannablisscream.com
  - platform: cert_expiry
    host: bakedwithbuddies.com
    name: bakedwithbuddies.com
  - platform: cert_expiry
    host: dabnap.com
    name: dabnap.com
### SSL Cert Check - hosted ###
  - platform: cert_expiry
    host: armbarassassin.com
    name: armbarassassin.com
  - platform: cert_expiry
    host: simplyeffectsmakeup.com
    name: simplyeffectsmakeup.com
  - platform: cert_expiry
    host: reliable-cable.com
    name: reliable-cable.com
  - platform: cert_expiry
    host: auntiekskitchen.com
    name: auntiekskitchen.com
  - platform: cert_expiry
    host: pinheadztradingpost.com
    name: pinheadztradingpost.com
  - platform: cert_expiry
    host: concernedinkanab.com
    name: concernedinkanab.com
  - platform: cert_expiry
    host: cannadiamond.com
    name: cannadiamond.com
  - platform: cert_expiry
    host: blog.optincall.com
    name: blog.optincall.com
  - platform: cert_expiry
    host: optincall.com
    name: optincall.com
#### Start MiFlora Sensors ####
  - platform: miflora
    mac: 'C4:7C:8D:62:3F:9D'
    name: Center Table
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:3F:2C'
    name: CatNip 1
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:63:61:40'
    name: CatNip 2
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:63:80:5C'
    name: Tilapia Tank
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:63:7B:60'
    name: Top Table
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6C:BA'
    name: Bottom Table
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6B:96'
    name: Rosemary
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:68:31'
    name: Pond
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6B:48'
    name: Tomato Pot
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:E9:6C'
    name: Passion Fruit
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:7E:D7'
    name: Tree 1
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6D:18'
    name: Tree 2
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6D:0C'
    name: Tree 3
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:7E:6E'
    name: Tree 4
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  - platform: miflora
    mac: 'C4:7C:8D:62:6C:AC'
    name: Tree 5
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
## Transmission ##
  - platform: transmission
    host: hive
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
### World Air Quality Index ###
  - platform: waqi
    token: !secret waqi
    locations:
      - Camp Pendleton
#    stations:
#      -
### OutSide IP ###
  - platform: rest
    scan_interval: 86400
    resource: http://ip.jsontest.com
    name: External IPv6
    value_template: '{{ value_json.ip }}'
  - platform: rest
    scan_interval: 86400
    resource: https://api.ipify.org
    name: External IPv4
  #  value_template: '{{ value_json.ip }}'
