###################################
##  LOG Medicine
###################################
alias: Frogs Fed
#hide_entity: False
initial_state: True
trigger:
  platform: state
  entity_id: input_boolean.fed_frog
  to: 'on'
  from: 'off'
action:
#    - service: automation.turn_off
#      entity_id: automation.log_medicine_activity
- service: logbook.log
  data:
    name: "Frogs Fed"
    message: "Got crickets."
-  delay:
    seconds: 15
- service: input_boolean.turn_off
  entity_id: input_boolean.fed_frog
# - service: notify.hive_orfg_med_log
#   data_template:
#     message: "{{ trigger.to_state.attributes.friendly_name }} taken at {{ states.automation.log_medicine_activity.attributes.last_triggered }}"
#     title: Took meds here is Chewy
#     data:
#       file:
#         url: http://catcam:8080/shot.jpg

#    - service: mqtt.publish
#      data_template:
#        payload: '{{ states("sensor.date") }}'
#        topic: 'dash/medicine/medicine_time'
#        retain: true

#    -  service: script.ifttt_notify
#       data_template:
#         value1: 'Took Medicine today.'

#    -  delay:
#         minutes: 1
#    - service: automation.turn_on
