- platform: miflora
  mac: 'C4:7C:8D:62:3F:9D'
  name: Don 1
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:62:3F:2C'
  name: CatNip 1
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:63:61:40'
  name: needtoplace
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:63:80:5C'
  name: Tilapaia Tank Sensor
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: 'C4:7C:8D:63:7B:60'
  name: Cactus
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
