### !include includes/templates/birthday_wishes.yaml ###
>
  {# Birthday Wishes #}
  {% macro getRandomBirthdayWish() -%}
    {{ [
       "Celebrate your birthday today. Celebrate being Happy every day.",
       "Well, you are another year older and you haven't changed a bit. That's great because you are perfect just the way you are. Happy Birthday.",
       "You are special and I hope that you float through the day with a big smile on your face. Happy Birthday!",
       "Happy Birthday!!! I hope this is the begining of your greatest, most wonderful year ever!",
       "Wishing you a day that is as special in every way as you are. Happy Birthday.",
       "You have to get older, but you don't have to grow up!",
       "Set the world on fire with your dreams and use the flame to light a birthday candle. HAPPY BIRTHDAY!",
       "Thinking of you on your birthday, and wishing you all the best! I hope it is as fantastic as you are, you deserve the best and nothing less.",
       "I hope that you have the greatest birthday ever from the moment you open your eyes in the morning until they close late at night.",
       "Hope your birthday is totally cool, really funtastic, wonderful, exciting, majorly awesome, rocking and HAPPY. Happy Birthday wishes.",
       "Be your own light. Find your own way. It should be easy with all those candles.",
       "Your birthday should be a national holiday. I need a day off. Happy Birthday.",
       "You are a gift to the world. How is that for a reverse birthday wish. Happy Birthday.",
       "I hope that today is the beginning of a great year for you. Happy Birthday.",
       "Happy Birthday !! Have a wonderful happy, healthy birthday and many more to come.",
       "I hope you have a beautiful day and get at least half of what you want! Happy Birthday!",
       "Happy Birthday. Just one more year and you will be perfect. Yes, I did say that last year.",
       "You have a birthday twinkle in your eye so have fun and know we love you fairy, fairy much. Happy Birthday.",
       "Live today like it is a special gift, because it is the best birthday gift. Happy Birthday.",
       "May your heart naturally beat with the happiness and laughter that you give others. Happy Birthday.",
       "Happy Birthday. Hope it's one of the best ever!!!!... a lovely birthday for a lovely person!",
       "Wishing you health, love, wealth, happiness and just everything your heart desires. Happy Birthday.",
       "Happy Birthday to a friend who means more to me than chocolate.",
       "Things I like about you: humor, looks, everything. Happy Birthday.",
       "Watch out world. You are old enough to know what to do and how to do it. Happy Birthday.",
       "When I paint my masterpiece, I am pretty sure there will be a spot for you. Happy Birthday.",
       "Happy Birthday. I hope that you will have a truly marvelous and joyous day with family and friends.",
       "Enjoy your birthday and every day to the fullest. A Happy Birthday is just part of a Happy Life.",
       "No matter how hard you try to fit in, you were born to stand out. Now celebrate that fact.",
       "Hope your day is simply terrific! Happy Birthday.",
       "I wish you a wonderfulBirthday!! I hope you have an amazing day and lots of fun! Enjoy this day, you deserve it!",
       "Time waits for no one but that doesn't matter if you don't wait for it! Happy Birthday.",
       "Today is not the end of another year, but the start of a new one. Happy Birthday.",
       "Being young is a privilege. Being attractive a genetic gift. Being cool, that is all you. Happy Birthday.",
       "Wishing you love and happiness on your birthday. Happy Birthday",
       "You aren't getting older, you are getting better. Happy Birthday.",
       "May your day be beautiful and may your heart be happy and may you celebrate birthdays for many years to come.",
       "I wish you happiness, health and so many good things in your life. Happy Birthday!",
       "Work hard. Play hard. Eat lots of cake. That's a good motto for your birthday and for life.",
       "I wish you happiness, health and so many good things in your life. Happy Birthday!",
       "What should we celebrate first: your accomplishments or your birthday?",
       "Out of the 19,178,082 people having a birthday today, you rank solidly in my top 10 list.",
       "Happy Birthday to a lovely & vibrant individual!",
       "You remind me of you at your age. Young and good looking! Happy Birthday!",
       "I wish you the best birthday ever! I hope you get lots of kisses and hugs. Happy Birthday!",
       "Hope you have wonderful birthday filled with fun, excitement and joy. Happy Birthday.",
       "I hope your BIG BRIGHT STAR keeps on shining. HAPPY BIRTHDAY !",
       "Happy Birthday. Hope it's one of the best ever!!! A lovely birthday for a lovely person!",
       "Happy moments. Happy thoughts. Happy Dreams. Happy feelings. Happy Birthday.",
       "Happy Birthday to you!, Happy Birthday to you!, Happy Birthday to you!"
       ] | random }}
  {%- endmacro -%}
  {{- getRandomBirthdayWish() -}}
